version: '3.1'

services:
  redmine:
    build: .
#    image: 'bitnami/redmine'
    ports:
      - '3000:3000'
    environment:
      REDMINE_USERNAME: admin
      REDMINE_PASSWORD: admin
      REDMINE_DATABASE_TYPE: postgresql
      REDMINE_DATABASE_HOST: db
#      REDMINE_DATABASE_HOST: production.czqqidnugvnf.ap-northeast-2.rds.amazonaws.com
      REDMINE_DB_PORT_NUMBER: 5432
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: postgres
#      REDMINE_DB_PASSWORD: PWSeS6kX
      REDMINE_DB_NAME: redmine
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redmine
    ports:
      - 5432:5432