version: '3.1'

services:
  redmine:
    build: .
#    image: 'bitnami/redmine'
    ports:
      - '3000:3000'
    environment:
      REDMINE_USERNAME: admin
      REDMINE_PASSWORD: admin
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: postgres
      REDMINE_DB_NAME: redmine
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PORT_NUMBER: 5432
    depends_on:
      - db
    volumes:
     - ./files:/bitnami/redmine/files

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redmine
    ports:
      - 5432:5432